[project]
name = "sybaritic"
version = "0.0.1"
description = "Async Spartan protocol client library"
readme = "README.md"
authors = [
    { name = "Dave Pearson", email = "davep@davep.org" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
sybaritic = "sybaritic.cli:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.4.0",
    "mypy>=1.10.0",
    "codespell>=2.3.0",
    "pre-commit>=4.6.1",
]
test = [
    "pytest>=8.0.0",
    "pytest-cov>=5.0.0",
    "pytest-asyncio>=0.23.0",
]
docs = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.7.7",
    "mkdocstrings[python]>=1.0.4",
]

